#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

for f in $(ls *.ko); do
	insmod $f
done

sysctl -w kernel.perf_event_paranoid=1

cat <<EOF


Boot took $(cut -d' ' -f1 /proc/uptime) seconds


EOF
chmod 600 /flag
chown 0.0 /flag
exec su -l ctf
